name: Backend CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - uses: actions/checkout@v2
    - run: |
        mkdir ./src/main/resources
        touch ./src/main/resources/application.properties
    - run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back .

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Hub Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Excute Remote SSH Commands Using SSH_PRIVATE_KEY
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back
            docker run -d -p 8080:8080 --name tabletop-backend ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back
            docker system prune -f
