name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: actions/checkout@v2
    - run: |
        mkdir ./src/main/resources
        touch ./src/main/resources/application.properties
    - run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  build-and-push-docker:
    needs: build-backend
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back:latest
        
  deploy:
    needs: build-and-push-docker
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back:latest
          docker stop tabletop-back || true
          docker rm tabletop-back || true
          docker run -d --name tabletop-back -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/docker-tabletop-back:latest
        EOF
        rm -f private_key.pem
